name: Build from Web

on:
  workflow_dispatch:
    inputs:
      subversion:
        description: 'Sub-version (eg: 46)'
        required: true
        type: string
      platform:
        description: 'platform'
        required: true
        default: 'All'
        type: choice
        options:
        - Android
        - Windows
        - IOS
        - Merged
        - All

jobs:
  windows:
    runs-on: windows-2022
    steps:
      run: |
        .\newb-builder-web.ps1