name: Windows 2022 Build

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
    inputs:
      subversion:
        description: 'Sub-version (eg: 46)'
        required: true
        type: string
      platform:
        description: 'platform'
        required: true
        default: 'All'
        type: choice
        options:
        - android
        - windows
        - ios
        - merged
        - all

jobs:
  build:
    runs-on: windows-2022
    env: 
      chicken: murgi
      platform: ${{ github.event.inputs.platform }}
      subversion: ${{ github.event.inputs.subversion }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variable
        run: |
          Write-Output "$env:chicken, $env:platform"

      - name: git clone
        run: |
          git clone --quiet https://${{ secrets.TOKEN }}@github.com/faizul118/newb-x-testing.git
          Move-Item "newb-x-testing\*" .


      - name: .\build.bat --no-zip -v ${{ github.event.inputs.subversion }} -p ${{ github.event.inputs.platform }}
        run: |
          switch ($env:platform) {
            'android' {
              Write-Output "Building for Android..."
              .\build.bat pack --no-zip -v ${{ github.event.inputs.subversion }} -p android
              Move-Item "build\pack-android\*" -Destination "build"
              Remove-Item "build\pack-android" -Recurse -Force
            }
            'windows' {
              Write-Output "Building for Windows..."
              .\build.bat pack --no-zip -v ${{ github.event.inputs.subversion }} -p windows
              Move-Item "build\pack-windows\*" -Destination "build"
              Remove-Item "build\pack-windows" -Recurse -Force
            }
            'ios' {
              Write-Output "Building for iOS..."
              .\build.bat pack --no-zip -v ${{ github.event.inputs.subversion }} -p ios
              Move-Item "build\pack-ios\*" -Destination "build"
              Remove-Item "build\pack-ios" -Recurse -Force
            }
            'merged' {
              Write-Output "Building for Merged..."
              .\build.bat pack --no-zip -v ${{ github.event.inputs.subversion }} -p merged
              Move-Item "build\pack-merged\*" -Destination "build"
              Remove-Item "build\pack-merged" -Recurse -Force
            }
            'All' {
              Write-Output "Building for all... (hmm... platform equality)"
              .\build.bat pack --no-zip -v ${{ github.event.inputs.subversion }} -p android
              .\build.bat pack --no-zip -v ${{ github.event.inputs.subversion }} -p windows
              .\build.bat pack --no-zip -v ${{ github.event.inputs.subversion }} -p ios
              .\build.bat pack --no-zip -v ${{ github.event.inputs.subversion }} -p merged
            }
            default {
              Write-Output "Unknown platform: $env:platform"
            }
          }

      - name: Upload artifact (${{ github.event.inputs.platform }})
        run: |
          echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        shell: bash

        uses: actions/upload-artifact@v4
        with:
          name: newb-x-testing-${{ github.event.inputs.platform }}-${{ env.CURRENT_DATE }}-${{ github.sha::7 }}
          path: ./build