name: Build from Web/Dispatch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
      - name: Set environment variables
    env:
      murgi: hello
        run: .\newb-builder-web.ps1












#      - name: Set environment variables
#        run: echo ${{ (github.event.inputs.platform == 'Windows')
#    if 
#    runs-on: windows-2022
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-python@v5
#        with:
#          python-version: '3.11' 
#          cache: 'pip'
#      - uses: actions/cache@v4
#        with:
#          key: env-files-win-laz
#          path: |
#            ${{ github.workspace }}/tool/data
#      - run: pip install -r requirements.txt
#      - run: |
#          .\build.bat setup
#          .\build.bat pack -p ${{ inputs.platform }} -v ${{ inputs.subversion }} --no-zip
#      
#      - uses: actions/upload-artifact@v4
#        with: 
#          name: mcpack
#          path: ./build/mcpack/