name: Windows 2022 Build

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
    inputs:
      subversion:
        description: 'Sub-version (eg: 46)'
        required: true
        type: string
      platform:
        description: 'platform'
        required: true
        default: 'All'
        type: choice
        options:
        - android
        - windows
        - ios
        - merged
        - all

jobs:
  build:
    runs-on: windows-2022
    env: 
      chicken: murgi
      platform: ${{ github.event.inputs.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variable
        run: |
          Write-Output "$env:chicken, $env:platform"

      # Run the PowerShell script newb-builder-web.ps1
      - name: .\build.bat --no-zip -p ${{ github.event.inputs.platform }}
        run: |
          switch ($env:platform) { 
          'android' { Write-Output "Building for Android..."; .\build.bat pack --no-zip -p android } `
          'windows' { Write-Output "Building for Windows..."; .\build.bat pack --no-zip -p windows } `
          'ios' { Write-Output "Building for iOS..."; .\build.bat pack --no-zip -p ios } `
          'merged' { Write-Output "Building for Merged..."; .\build.bat pack --no-zip -p merged } `
          'All' { Write-Output "Building for all... (hmm... platform equality)"; `
          .\build.bat pack --no-zip -p android; `
          .\build.bat pack --no-zip -p windows; `
          .\build.bat pack --no-zip -p ios; `
          .\build.bat pack --no-zip -p merged } 
          }

