name: Windows 2022 Build

on:
  workflow_dispatch:
    inputs:
      subversion:
        description: 'Sub-version (eg: 46)'
        required: true
        type: string
      platform:
        description: 'platform'
        required: true
        default: 'All'
        type: choice
        options:
        - Android
        - Windows
        - iOS
        - Merged
        - All

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variable
        env: |
          chicken: murgi
        run: |
          Write-Output $env:chicken
          echo "MURGI=hello" >> $env:GITHUB_ENV
          echo "PLATFORM=${{ github.event.inputs.platform }}" >> $env:GITHUB_ENV

      # Run the PowerShell script newb-builder-web.ps1
      - name: Run newb-builder-web.ps1
        run: |
          .\newb-builder-web.ps1
