name: Build from Web/Dispatch

on:
  repository_dispatch:
    types: [trigger-action]
  workflow_dispatch:
    inputs:
      subversion:
        description: 'Sub-version (eg: 46)'
        required: true
        type: string
      platform:
        description: '-p argument'
        required: true
        default: 'merged'

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
          cache: 'pip'
      - uses: actions/cache@v4
        with:
          key: env-files-win-laz
          path: |
            ${{ github.workspace }}/tool/data
      - run: pip install -r requirements.txt
      - run: |
          .\build.bat setup
          .\build.bat pack -p ${{ inputs.platform }} -v ${{ inputs.subversion }} --no-zip
      
      - uses: actions/upload-artifact@v4
        with: 
          name: mcpack
          path: ./build/mcpack/